### ISSUE TITLE
broken upgrade

### ISSUE THREAD

**Issue by qaisjp** [neanias/proj-webapp#6]
c854877a69eb5c3eb5d4cdaf7c3d5607782d5d1e works (+ `yarn upgrade node-sass`)

latest master (c34c133d6d023cbfe7b8510deb15903ebe6adc05) is broken

"broken" = css does not compile and therefore causes console error

"broken" = the shield is black by default and inserting some text is still black

`_parse` query works fine tho

**Comment by neanias** [comment]
Yeah, I haven’t really looked into fixing this. Thanks for the reminder!

**Comment by neanias** [comment]
Fixed with latest push
